### ISSUE TITLE
New Create/Edit Page should display blank page

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#237] opened 2015-05-05 16:05 UTC
Display a listing in Listing Management.
Using the triple lines, click on Submit a Listing
Page display the data from the previous listing.  It should display a blank page.

**Comment by clarkjefcoat** [comment] 2015-05-07 19:51
I'm closing this issue as it is a duplicate of #151

**Closed by clarkjefcoat** 2015-05-07 19:51 UTC
