### ISSUE TITLE
Listing Management - Org tab is showing for all users

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#186] opened 2015-04-09 17:01 UTC
In Listing Management, general user selects the organization tab at the top.  Pop up box message displays, “You are not authorized to view this page”.  User clicks the Ok button and is taken to the Center page.  Clicking the OK button should close the pop up box and leave the user in List Management.  However, if the user is not allow to access the organization tab because they are not an org. content steward, why should they be allow to see the tab at all.

**Comment by sdeighan** [comment] 2015-04-09 17:11
The organization tab should not be visible to general users - it is appearing when it should not.

**Comment by wski** [comment] 2015-04-09 19:20
When trying to access the page as a general user I do not see an organization tab. however by directly accessing http://localhost:8000/dist/#/user-management/all-listings i was able to get the popup, but after clicking okay I was routed to the homepage.

**Comment by tonyalletag** [comment] 2015-04-10 16:50
This bug exit in our STG environment.  The tabs are displayed. When clicked I get the popup and redirected to the home page

Steps to reproduce:
Make yourselft and OZP Admin
Make your self and ORG Steward of an organization 
Remove your OZP Admin role
Tabs are view but redirect you the home page

Expected results:
Tabs should not be viewable if you don't have access to them

**Comment by rpokorny** [comment] 2015-04-10 16:55
Sounds like this happens because the tab logic is only checking what orgs the user has in the stewardedOrganizations collection, and not also checking that the user is in fact an Org Steward (or admin)

**Comment by mparizernc** [comment] 2015-04-10 18:21
I agree this is a bug and should be fixed but is this something that really needs to be fixed for IOB.  Are we really going to be switching roles that often and if you are shouldn't someone be letting the person administrating know to remove the Org from you ahead of time.  This will only happen to a very few people.  Seems to me we should be concentrating on bugs that will affect more users with greater impact.

**Comment by tonyalletag** [comment] 2016-03-01 18:28
Need to look at this again

**Comment by rkenyon1969** [comment] 2016-04-21 17:58
@clarkjefcoat - can you walk me through Tony's steps:

Steps to reproduce:
Make yourselft and OZP Admin
Make your self and ORG Steward of an organization 
Remove your OZP Admin role
Tabs are view but redirect you the home page

Expected results:
Tabs should not be viewable if you don't have access to them

**Comment by clarkjefcoat** [comment] 2016-04-21 19:41
@rkenyon1969: The steps that Tony describes are applicable only in our staging environment.  They assume that you have the ability to easily edit the data in a demo authentication server.  We do not currently have that ability in dev.

Someone with access to the staging will have to test this.

**Comment by rkenyon1969** [comment] 2016-04-21 19:41
@clarkjefcoat - thanks

**Comment by tdressel** [comment] 2016-05-20 14:30
I did test on LS that general users can't see the Org Tab in Listing Management.  Will test removing roles on staging environment.

**Comment by tdressel** [comment] 2016-07-12 19:29
Passed on Staging. 
General User-
Pop Up Detail | Admin Tab - X
Menu Drop Down | Center Settings and Metrics - X
Listing Management | All Center Listings Tab - X

Org Steward-
Pop Up Detail | Admin Tab - X
Menu Drop Down | Center Settings and Metrics - X
Listing Management | Org Listings Tab - ✓

Admin-
Pop Up Detail | Admin Tab - ✓
Menu Drop Down | Center Settings and Metrics - ✓
Listing Management | All Center Listings Tab - ✓

**Closed by tdressel** 2016-07-12 19:29 UTC
Labels: 0 - Backlog, bug, Can't reproduce, newbie
