### ISSUE TITLE
Cancel delete from Create/Edit page routes to new listing

### ISSUE THREAD

**Issue by stephanieerin** [ozone-development/ozp-center#98] opened 2015-02-27 17:47 UTC
When you create a listing, save, and then delete it, the page routes to 'edit' which results in the data you had previously entered being lost.

**Comment by nishp1** [comment] 2015-03-06 18:27
Cannot reproduce.

**Comment by mparizernc** [comment] 2015-03-06 19:23
Steps to Reproduce:
1) Create a new listing 
2) Save
3) Stay on the from and make edits
4) Hit delete and then cancel
5) The form clears out

**Comment by nishp1** [comment] 2015-03-06 21:31
@mparizernc pushed the fix to `temp-master`.

**Comment by mparizernc** [comment] 2015-03-10 14:00
I am still seeing the same behavior the URL is not reloading with the listing id.

**Comment by nishp1** [comment] 2015-03-10 14:14
Fyi..Fix I had put in didn't required URLs to change by just checking that you are still on /edit page. Look at routers transition methods.

**Comment by mparizernc** [comment] 2015-03-11 15:22
All Browsers

Following the steps to reproduce the issue is no longer happening.  Verified deleting listings from other places works as well.

**Closed** 2015-04-06 15:28 UTC
Labels: 5 - Done, bug
