### ISSUE TITLE
Search & Discovery - Categories should be sorted into alphabetical order

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#46] opened 2015-02-13 17:58 UTC
Center catagories are not sorted. New categories will always be added to the end of the list.  We need to be able to re-order categories without taking the system down.

**Comment by rpokorny** [comment] 2015-02-13 18:01
> We need to be able to re-order categories without taking the system down.
Should they be arbitrarily re-orderable by an admin, or simply sorted in some defined way (such as alphabetical)?

**Comment by tonyalletag** [comment] 2015-02-13 19:03
We need the a UI/UX person or the Product Owner to make that call

**Comment by nishp1** [comment] 2015-02-13 19:04
What did the reporter of the bug in our testing expect?

**Comment by sdeighan** [comment] 2015-02-18 22:33
By industry and general information architecture standards, categories should be displayed in alphabetical order and I can't think of any reasons not to follow that precedent in this case.

**Comment by mparizernc** [comment] 2015-02-26 17:01
I am moving this to an enhancement as this is not a bug but new desired functionality.

**Comment by tonyalletag** [comment] 2015-06-09 19:48
The categories should be alphabetized

**Comment by clarkjefcoat** [comment] 2015-06-19 19:45
This issue was moved to ozone-development/ozp-rest#81

**Closed by clarkjefcoat** 2015-06-19 19:45 UTC
Labels: 2 - Working, enhancement
