### ISSUE TITLE
Create/Edit Page - Add "Singleton" to the Details section

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#199] opened 2015-04-16 19:58 UTC
# Add a toggle to indicate whether or not this listing is a "Singleton" in Webtop

## Is not a Singleton
![mp_createeditform_details_singletonnot](https://cloud.githubusercontent.com/assets/7987446/7204494/b34f4e48-e4f0-11e4-9b41-928dacf4fe19.png)

## Is a Singleton
![mp_createeditform_details](https://cloud.githubusercontent.com/assets/7987446/7190063/5efe59e6-e451-11e4-9f65-434dfb739d94.png)

**Comment by hoganmaps** [comment] 2015-06-04 19:31
This works

**Comment by clarkjefcoat** [comment] 2015-06-04 21:23
On ci-master, staging and prod there is a problem with the descriptive text on initial load when Singleton is set to true.  A fix for this is already available on ci-develop and will be included in the next release.

**Comment by kgordon-1** [comment] 2015-06-12 16:34
This was working in STG and now it is not.  Ticket 579 address that the wrong error message was displayed.

**Comment by wski** [comment] 2015-06-15 17:47
@kgordon-1 can you give me more context to an error message (#579 cannot be found) this ticket is in regards to adding a toggle to enable or disable singleton mode for submissions, there should be no error reporting associated because there is no way to have an invalid input for this component, Since it is not required and only shows on, or off. Also it will default to an acceptable value of off / false.

**Comment by mparizernc** [comment] 2015-06-26 14:38
@wski Not sure what the bug from above is but the filed was not added to the tree on the left side under intents meaning you can't navigate to it from the accordion menu.

**Comment by blaino** [comment] 2015-07-08 12:53
@wski, I'm not exactly sure what to test here. As for the last few comments regarding "Singleton" appearing in the accordion menu, I can confirm that it's there on ci-develop, but it's also present on ci-master, so I'm not sure what is being fixed. As for this ticket as a feature request for the addition of a Singleton listing area on the create/edit page, I believe that's already been tested?

**Comment by blaino** [comment] 2015-07-08 14:28
Ok, looks like the change has been around for a while. Moving to CI-QA.

**Comment by mparizernc** [comment] 2015-07-16 18:33
Verified the ticket in staging with all of the browsers.

I did find a bug in where the activity is not getting recorded. The issue is 88 in ozp-rest.

**Closed** 2015-10-12 15:20 UTC
Labels: 4 - CI-QA
