### ISSUE TITLE
Create/Edit Page - PoC Associated Organization field delete bug

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#256] opened 2015-05-15 14:21 UTC
In listing Management, in the contact section click on Add New
Enter characters or a phrase into the Associated Organization field.  
    Use the backspace to delete the characters the following happens:
 
        Holding the backspace key down, start to deleted but half way it starts to jump and display characters that were deleted.
        Not all ways able to delete the last letter left.

**Comment by sdeighan** [comment] 2015-05-15 14:59
The associated organization field is a dropdown menu; a user should not be able to just delete characters.

I tried to reproduce this bug while typing in dropdown menu's search box, but I was unable to reproduce in development.

Any additional details?

**Comment by sdeighan** [comment] 2015-05-15 15:09
@mparizernc suggested that this could be the Point of Contact's "Associated Organization" field, so I tested it in development and I was able to reproduce it. If you type something into PoC's Associated Organization field, you can't delete the last character

**Comment by kgordon-1** [comment] 2015-05-15 15:22
There are 2 fields with the same name.  The field I am referring to you
have to click add new under contact

**Comment by blaino** [comment] 2015-07-07 19:46
Same issue as #256.

**Comment by wski** [comment] 2015-07-07 22:27
verified it's working on my end, passing to CI-QA

**Comment by mparizernc** [comment] 2015-07-16 15:57
@blaino I was testing this on staging and realized that the Organization never gets saved for the Contact.  So technically I am able to delete the last character but the field it self gets nulled out every time it is saved.  I confirmed on an earlier build that this was saving properly before.

**Comment by blaino** [comment] 2015-07-16 18:14
@mparizernc Yes, I think we've seen this over here too. #324, still waiting for peer review, I think, will fix this.

**Comment by blaino** [comment] 2015-07-16 20:14
@mparizernc, I think this is fixed now. I've tested ci-develop on chrome, ie9, and ie11. I tested by entering just enough information to save and checking the preview details tab. In particular, I checked that you could delete the last character in What's New AND see the saved Organization and What's New in the preview. I anxiously look forward to your test.

**Comment by mparizernc** [comment] 2015-07-17 19:13
Verified this is all working on Develop in all of the browsers.

**Comment by mparizernc** [comment] 2015-07-29 16:18
Verified on staging that I was able to delete all of the characters for the contact organization.  (IE9, FF, Chrome)

**Closed** 2015-10-12 15:18 UTC
Labels: 2 - Working, bug
