### ISSUE TITLE
Create/Edit Page - Need duplicate name error message

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#156] opened 2015-03-26 14:29 UTC
1. Open Marketplace
2. Click on "Air Mail" and open Detailed View
3. Click the "edit" button and load the Create/Edit page
4. Go to the Global Toolbar, click the main menu icon, and then click the "Submit a Listing" link
5. An error will have popped on the "Name" field (which is currently populated with "Air Mail") saying "May contain letters, numbers or symbols and must be 60 characters long or less."
6. Add a space to the end of the name field (so that it says "Air Mail ") and the error will go away

We really need a more accurate error message if we do not allow listings with duplicate names

**Comment by mparizernc** [comment] 2015-03-31 11:23
I believe there is some other issue going on here because unless someone changed the behavior duplicate listing names are allowed.  What if you have 2 versions of the same App shouldn't they be the same name and just have different versions.

**Comment by stephanieerin** [comment] 2015-04-15 17:16
This seems to have been fixed in some other thing, I've successfully made a few different listings with the same name (which is expected behavior).

**Comment by mparizernc** [comment] 2015-04-16 11:42
Actually I figured out what was going on here. This is not an issue with duplicates. I looked closer at your steps and this issue is a duplicate of #151. What is happening is that when you are on the Edit page and try and then hit Submit a Listing the page is not being properly refreshed and therefore you are seeing the error that you see.  I am going to close this since the fix for #151 will fix this as well and this is just a duplicate.

**Closed** 2015-04-16 11:43 UTC
Labels: 5 - Done, bug-IOB
