### ISSUE TITLE
Recent Activity - Change to Screenshot field not in list

### ISSUE THREAD

**Issue by jloveland18** [ozone-development/ozp-center#179] opened 2015-04-08 15:43 UTC
1. Create listing
2. Org content steward select the triple line drop down menu on the right side of the toolbar and chooses listing Management
3. Select the 'recent Activity' tab. On the left hand side select "Pending Organization review". 

Expected result: The created listing is shown as a Screenshot.
Current result: The created listing is shown as a blank box.

**Comment by stephanieerin** [comment] 2015-04-15 18:02
I created a listing with all different images (as a user), logged in as the org steward and went to recent activity and then clicked through to "pending TO review" and the correct icon showed up. Am I missing something?

**Comment by stephanieerin** [comment] 2015-04-15 18:28
Also checked that when I have a listing and I edit the screenshot it appears correctly on the Recent Activity page, if that's what this is referring to.

**Comment by jloveland18** [comment] 2015-04-16 12:16
Hi Stephanie..we we had some weird issues from time to time where the image a screenshot wouldn't show up..it'd just be a blank square..and the weird thing is, once it showed up in your listings, u coudn't edit or delete it..clark had to go in and delete it manually..i'm not seeing the behavior right now but if i do again, i'll let u know.

**Comment by clarkjefcoat** [comment] 2015-05-15 16:30
Closing as 'Can't Reproduce'.

**Closed by clarkjefcoat** 2015-05-15 16:30 UTC
Labels: bug, bug-IOB, Can't reproduce
