### ISSUE TITLE
Create/Edit Page Secure number display error and will not save

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#228] opened 2015-04-30 13:02 UTC
In staging, created a listing, completed all required fields, 
Selected Add New for Contacts and completed all required fields.
Selected Add to New to add another contact completed required fields.  
In the Secure Number field type in 3333333333 which is a valid number and the field stayed red.  
Typed in 333-333-3333 and no change, tried to save and what not allow the save feature to work.

**Comment by sdeighan** [comment] 2015-05-11 16:47
Unable to reproduce in development - do you have any additional details? Or does anyone know if this was this solved by another bug fix last week?

**Comment by tonyalletag** [comment] 2015-06-05 13:28
Can we close this?

**Comment by wski** [comment] 2015-07-15 18:44
I was also unable to reproduce, due to the age of the ticket and lack of ability to reproduce I would suggest we close this.

**Closed** 2015-10-12 17:07 UTC
Labels: bug
