### ISSUE TITLE
Create/Edit Page - Listing Intermittently doesn't save

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#196] opened 2015-04-15 15:38 UTC
_From @jloveland18 on March 13, 2015 15:55_

Steps to Recreate:
1. Click on the three Horizontal lines in the top right corner.
2. Select submit listing.
3. Fill in name and listing type.
4. Select save.
5. Click on the three Horizontal lines in the top right corner.
6. Select listing Management.
7. Find the box with today's date.
8. Select the drop down arrow on the top right corner of the box and select edit.
9. Completely fill out the form (under Graphics -> Screenshots make sure you select 'add' and add two Screenshots- this is Mandatory or else you can't save Successfully).
10. Select save.

Current Behavior: Sometimes the listing saves the first time and Sometimes you have to keep trying Several times before the listing finally saves.
Expected Behavior: The listing should save on the first try.

_Copied from original issue: ozone-development/ozp-webtop#485_

**Comment by wski** [comment] 2015-04-30 17:47
This works every time for me, is this happening on a local deployment as well? This seems like it's a infrastructure issue

**Comment by wski** [comment] 2015-04-30 17:55
Also tried to reproduce on staging but could not

**Comment by wski** [comment] 2015-04-30 18:12
@jloveland18 can you try to reproduce this on ci-master

**Comment by arw180** [comment] 2015-06-05 14:14
also failed to reproduce. tried saving many times in many different fields with different browsers.

**Comment by kgordon-1** [comment] 2015-06-11 17:52
Follow the above directions and tried to reproduce.  Still unable to reproduced and since no one has been able to reproduce this situation, closing ticket.

**Closed** 2015-06-23 13:46 UTC
Labels: 6 - Done, bug, Can't reproduce, IOB
