### ISSUE TITLE
Listing Management - Delete confirmation stops appearing after deleting 2 listings

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#146] opened 2015-03-24 13:54 UTC
Attempting to delete more than 2 apps from the Listing Management screen does not work.  After 2 deletes the "Are you sure you want to delete?" confirmation pop-up no longer appears.

**Comment by tonyalletag** [comment] 2015-10-12 18:15
@jal-vsi - can you confirm this is still a bug?

**Comment by jal-vsi** [comment] 2015-10-13 12:23
It is still a bug.  After deleting one listing you cannot delete another
until you: 1) refresh the page, 2) select view, then delete, 3) select
Listing Management and then try to delete, etc.

On Mon, Oct 12, 2015 at 2:15 PM, tonyalletag <notifications@github.com>
wrote:

> @jal-vsi <https://github.com/jal-vsi> - can you confirm this is still a
> bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ozone-development/ozp-center/issues/146#issuecomment-147480290>
> .
>



-- 

Thanks,

Jim Laughter

Systems Test

Ventura Solutions Inc.

131 National Business Parkway

Suite 120

Annapolis Junction, MD 20701

(301) 623-4156

jlaughter@vsi-corp.com

**Comment by clarkjefcoat** [comment] 2015-10-15 18:07
@jal-vsi - Can you give more details on how to reproduce this bug?

I tried on the latest version of Chrome.  It was incredibly slow, but I did not notice any errors.

**Comment by jal-vsi** [comment] 2015-10-15 18:41
The delete function is working today beyond 2 listings.  Recommend closing
this issue.  The steps I did take Monday were:
IE9/11, FF, CH: Admin selects Listing Management, selects pull down/delete,
confirm Delete, try to select pull down/delete for another listing.

On Thu, Oct 15, 2015 at 2:07 PM, clarkjefcoat <notifications@github.com>
wrote:

> @jal-vsi <https://github.com/jal-vsi> - Can you give more details on how
> to reproduce this bug?
>
> I tried on the latest version of Chrome. It was incredibly slow, but I did
> not notice any errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ozone-development/ozp-center/issues/146#issuecomment-148475634>
> .
>



-- 

Thanks,

Jim Laughter

Systems Test

Ventura Solutions Inc.

131 National Business Parkway

Suite 120

Annapolis Junction, MD 20701

(301) 623-4156

jlaughter@vsi-corp.com

**Comment by akonsowski** [comment] 2016-04-11 20:18
I was not able to reproduce this issue on Chrome or Firefox. I followed steps and deleted 5 listings.

**Comment by tdressel** [comment] 2016-04-12 18:50
Deleted 8 apps successfully.  Passed.

**Comment by tdressel** [comment] 2016-06-09 15:55
Passed on staging.

**Closed** 2016-06-09 15:55 UTC
Labels: bug
