### ISSUE TITLE
Create/Edit Page - Navigation Tabs need to follow user

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-center#155] opened 2015-03-26 14:22 UTC
As a user scrolls down the Create / Edit form, the tabs need to close tabs reflecting a section that the user is leaving and open the tab with the section that the user is entering.

e.g. John completes the Basic Information section and tabs into the "Version Number" field.
-> Desired Behavior: the "Basic Information" tab closes and the "Listing Details" tab opens.

**Comment by mparizernc** [comment] 2015-04-15 13:22
closed by accident

**Comment by kgordon-1** [comment] 2015-04-15 14:19
Hi Mike, can you send me your address and number

**Comment by mparizernc** [comment] 2015-04-15 14:23
@kgordon-1 Sent it to you on Slack

**Comment by mparizernc** [comment] 2015-04-22 15:25
The scrolling seems fine however when I click on the Owners and Contacts tab it takes you there but it expands the graphics tab not the Owners and Contacts.

**Comment by wski** [comment] 2015-04-23 22:30
This is because of the spacing in the form, be design it shows the top most element that lines up to where it scrolls when you click, since the section is so small and at the bottom of the screen this will expand the wrong section. Perhaps we should come up with a percentage based bottom margin to make sure this issue is solved for the future @sdeighan had added spacing manually to fix this on most displays but the issue is still present on larger ones. @sdeighan what do you think about adding space dynamically depending on the viewport height?

**Comment by wski** [comment] 2015-04-30 16:06
So after talking to @TheAndyStumpf about this as well as @arw180 the conclusion was that we add a considerable amount of padding to the bottom of the form to fix this issue for now. Post IOB the layout of this page will likely change so it is not worth putting a considerable amount of work into making it dynamic.

**Comment by arw180** [comment] 2015-06-05 14:03
Verified on IE9, IE11, FF 24, and Chrome 43

**Comment by kgordon-1** [comment] 2015-06-11 18:25
Tested on STG
Verified fixed by scrolling down the Create/Edit screen.  The system displayed the correct information for each sections.

**Closed** 2015-06-23 13:46 UTC
Labels: 6 - Done, Feature, IOB
