### ISSUE TITLE
Search and Discovery -  Hitting the "Home" link should clear all filters

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#128] opened 2015-03-16 12:27 UTC
Hitting the "Home" link should clear the search box and all filters, but what happens now is that it does not clear the Organization or Listing Type filters. Those filters are still applied when you hit home if they were selected.

**Comment by tonyalletag** [comment] 2015-06-05 13:34
This looks fixed on production

**Comment by clarkjefcoat** [comment] 2015-06-05 20:16
The issue is that "Listing Type" and "Organizations" are not cleared.  That is still an issue.

**Comment by clarkjefcoat** [comment] 2015-07-08 20:57
For more on this issue see #308.  Will mark this as a dup even though it is older as most of the conversation has occurred on the other ticket.

**Closed by clarkjefcoat** 2015-07-08 20:57 UTC
Labels: bug, duplicate
