### ISSUE TITLE
Create/Edit Page: Save feature will not save 

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#254] opened 2015-05-15 13:09 UTC
Save feature will not save if contact required fields are not populated.  The system things its an error.
click on Add New under contact.  
Leave some of the required fields blank and click save

**Comment by sdeighan** [comment] 2015-05-15 13:44
@kgordon-1 
Could you provide any additional detail on this?
Does this affect any particular fields or all of the required fields?

**Comment by wski** [comment] 2015-07-15 21:31
I was unable to reproduce this bug, saving worked fine with no contacts. Is this still an issue or should we close? cc @clarkjefcoat

**Comment by clarkjefcoat** [comment] 2015-07-16 18:45
To reproduce:

1.  As admin go to Center Settings and the Contact Types tab
2.  Edit (or Add) a Contact Type and set Required to true
3.  Go to Submit a Listing, fill in all required fields except Contacts
4.  Choose Add New contact and choose a required Contact Type
5.  Partially fill-in the contact info (for example, Name, but not Email)
6.  Press Save

You will not be allowed to save.  You should be able to save a partially filled-in required Contact Type.

Do not close.  This is still a bug.

**Comment by mparizernc** [comment] 2015-07-16 19:06
Moved back to Ready so that it can be worked on when it is ready.

**Comment by tonyalletag** [comment] 2015-10-12 17:06
@clarkjefcoat & @mparizernc  I can't reproduce this on staging. Can this be closed

**Comment by mparizernc** [comment] 2015-10-12 17:08
I will defer to @clarkjefcoat since he was the one that was able to reproduce this before.

**Comment by clarkjefcoat** [comment] 2015-10-13 15:15
This bug is easily reproduced following the steps in my July 16 comment.

There does seem to be an improvement over the original situation because now Email and Phone are marked as required fields.  So while it won't save, it does give you an error message.

@tonyalletag - The ticket is based on the idea that "You should be able to save a partially filled-in required Contact Type."  If that is no longer a requirement, then this ticket can be closed.

**Comment by tonyalletag** [comment] 2016-01-14 16:43
Partial contact info should not be saved in this form

This form has become complex with portion markings and additional fields.  Adding logic to validate partial contact info will add additional complications.

**Closed by tonyalletag** 2016-01-14 16:43 UTC
Labels: bug
