### ISSUE TITLE
Global Toolbar - Shrinking the window pushes edge icons out of sight

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#164] opened 2015-03-30 19:10 UTC

**Comment by sdeighan** [comment] 2015-03-30 19:13
Any additional detail? In trying to reproduce, icons get squished in the listing management filters but this sounds worse.

**Comment by wski** [comment] 2015-03-30 19:15
Specifically in the global navbar

**Comment by sdeighan** [comment] 2015-03-30 19:17
Could you grab me a screenshot? I'm not able to reproduce anything that matches this description in Chrome or Firefox (on Mac)

**Comment by clarkjefcoat** [comment] 2015-03-30 19:21
In FF 36.0.4 in Ubuntu if I make the center small enough then I lose the HUD icon and the dropdown menu from the top navigation bar.

![image](https://cloud.githubusercontent.com/assets/7015118/6904622/378d18ca-d6f0-11e4-8351-a83bda543acb.png)

**Comment by wski** [comment] 2015-03-30 19:26
I get the same thing clark posted on Chrome / FF mac. Not sure how the global bar is styled but it seems this could be fixed by wrapping the icon row in a container element

**Comment by sdeighan** [comment] 2015-03-30 19:28
Ah, ok. So this is different than what was reported before; this one occurs anytime that the browser is narrower than about 800px wide. Until then, you can see most of the icons.

**Comment by sdeighan** [comment] 2015-03-31 02:40
Toolbar itself is fixed, but the header then stacks when the toolbar is fixed appropriately.

**Comment by sdeighan** [comment] 2015-03-31 02:52
Header no longer stacks at 1240px wide but "Organization" filter and "Listing Type" filters are hidden at lower widths because the fields are not responsive.

**Comment by sdeighan** [comment] 2015-04-15 14:49
Icons now fixed, but the rest of the screen will need to be considered at a later date.

**Closed** 2015-04-16 20:49 UTC
Labels: 5 - Done, bug, IOB, styling
